### ISSUE TITLE
fails to find out what scopelint does

### ISSUE THREAD

**Issue by siddharth178** [kyoh86/exportloopref#12]
Hi,

As suggested on `scopelint`'s site its obsolete now, `exportloopref` is what someone should use. So I am trying it on very simple code and it doesn't seem to work as expected.

Here is the code I am trying
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello!")

	letters := []string{"a", "b", "c"}
	funcs := []func(){}
	for _, l := range letters {
		funcs = append(funcs, func(){
			fmt.Println(l)
		})
	}
	for _, f := range funcs {
		f()
	}
}
```

scopelint sees the error
```
$ scopelint ./...
main.go:14:16: Using the variable on range scope "l" in function literal
Found 1 lint problems; failing.
```

but exportloopref doesn't report anything. like scopelint, I expect same error from exportloopref.
```
$ exportloopref  ./...
```

What might be going wrong?

**Comment by kyoh86** [comment]
It is not supported with exportloopref.
I want to make exportloopref as accurately as possible.

**Comment by siddharth178** [comment]
I thought `scopelint` checks will be available in `exportloopref` and I find check done on above code by `scopelint` important. It would really help if you could give some more context on why that kind of check is not part of `exportloopref`. @kyoh86

**Comment by kyoh86** [comment]
I found that diagnostics are just noise while a lot of false-positives are included.

- Any analyzer CANNOT know if a closure is called soon.
- So any variables in closures in the loop will be reported.

For example, scopelint reports a diagnostic on `testcase.expect`:

```
for _, testcase := range []struct {
	title string
	expect int
} {
	t.Run(testcase.title, func(t *testing.T) {
		actual := FUT()
		if testcase.expect != actual { // !!
			t.Errorf("
		}
	})
}
```

but it's not a problem (false-positive).

**Comment by kyoh86** [comment]
see also: https://github.com/kyoh86/scopelint/issues/16#issuecomment-765103943

**Comment by siddharth178** [comment]
Thanks @kyoh86  for the details!

**Comment by ziccardi** [comment]
@kyoh86 I think your example code should be reported at least as a warning. 

While it is true that it is not an issue with your code, if you would just add `t.Parallel()` at the beginning of the test function it won't work anymore.

**Comment by kyoh86** [comment]
I could not found them without false-positives.
You can propose an implementation by pull-request.
