### ISSUE TITLE
False positive when exporting a pointer to a loop variable field.

### ISSUE THREAD

**Issue by joeblubaugh** [kyoh86/exportloopref#18]
Like so:
```go
package main

import "fmt"

func main() {
	type S struct {
		I int
	}

	structs := []S{S{1}, S{2}}

	var myI *int
	for _, s := range structs {
		myI = &s.I
	}

	fmt.Println(*myI)
}
```

We do this a fair amount in my team's code, and it feels awkward to introduce a second variable like 
```go
i := s.I
myI = &i
```
 or to use a  `//nolint` directive.

**Comment by kyoh86** [comment]
This is a linter to find the matter like such code.
Please read README.md.
