### ISSUE TITLE
 No reports about using variable on range scope in function literal  (deprecated `scopelint` finds it perfectly)

### ISSUE THREAD

**Issue by mowtschan** [kyoh86/exportloopref#21]
Hi,

`scopelint` is deprecated and `exportloopref` is recommended as replacement.
Could the issue be fixed here or is it out of scope of `exportloopref` analyzer?

### Sample code:
```
package main

import "fmt"

func main() {
	var pipeline []func()

	for _, s := range []string{"a", "b"} {
		pipeline = append(pipeline, func() {
			fmt.Printf("%s\n", s)
		})
	}

	for _, f := range pipeline {
		f()
	}
}

# Output:
# 
# b
# b
```

### Expected analyzer report(like from `scopelint`):
`Using the variable on range scope 's' in function literal`

**Comment by kyoh86** [comment]
`exportloopref` cannot find them without false positive.
If you want it, you can make PR for `looppointer`.
`exportloopref` and `looppointer` have different policy.
