### ISSUE TITLE
Is this still valid with per-iteration loop variables?

### ISSUE THREAD

**Issue by andig** [kyoh86/exportloopref#24]
If not, might be nice to never fail depending on Go version.

**Comment by kyoh86** [comment]
You have the option of not using this.
The golangci-lint or go vet has the ability to choose which linter to use.

exportloopref does not verify that the target go source can be built with any version of go.
It only knows what version of go runtime the exportloopref is running.
It may not be the same one.

**Comment by kyoh86** [comment]
If you want, you can switch this linter with version info in the `go.mod`.
